### ISSUE TITLE
two layers with the name merge2

### ISSUE THREAD

**Issue by yhenon** [DT42/squeezenet_demo#3]
On line 47 of model.py you have:

```
merge2 = merge(
    [fire3_expand1, fire3_expand2], mode='concat', concat_axis=1)
```

I believe this should be:

```
merge3 = merge(
    [fire3_expand1, fire3_expand2], mode='concat', concat_axis=1)
```

since there already exists a merge2 layer on line 35. Renaming it to merge3 should reduce ambiguity.

**Comment by tammyyang** [comment]
The pull request to rename it has been accepted, and maxpool4 is also properly connected to merge3 instead of merge2. Close the issue.
