### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by phongnhhn92** [DT42/squeezenet_demo#5]
Hello sir,
I tried to run the file squeezenet_demo.py but i encountered some error about import. Would you mind telling me how to install simdat.core because i cant find anywhere in your code.
Also i didnt see you mention anywhere about the place you put your labels file of your training data. Can you tell me how you did it also.
Thank a lot man !

**Comment by tammyyang** [comment]
Hi, simdat package can be found here https://github.com/tammyyang/simdat. Sorry, I have no time to maintain and polish it at this moment. If you encounter any import error, please paste the error messages and I will take a look.

For the label file, we use the standard ImageNet.

**Comment by tammyyang** [comment]
ERPlite <support@erplite.com>
9:16 AM (4 hours ago)￼
￼
Tammy......trying squeezenet for keras on an RPi3....but get....

@raspberrypi:~/RasPiRobot/squeezenet_demo-master $ python squeezenet_demo.py --action='predice'\
>     -p /db/Roasted-Broccoli-Pasta-Recipe-5-683x1024.jpg
Traceback (most recent call last):
  File "squeezenet_demo.py", line 16, in <module>
    from simdat.core import dp_tools
  File "/usr/lib/python2.7/dist-packages/simdat/core/dp_tools.py", line 8, in <module>
    from simdat.core import image
  File "/usr/lib/python2.7/dist-packages/simdat/core/image.py", line 8, in <module>
    from simdat.core.so import math_tools
ImportError: /usr/lib/python2.7/dist-packages/simdat/core/so/math_tools.so: wrong ELF class: ELFCLASS64

**Comment by tammyyang** [comment]
Tammy Yang <tammy@dt42.io>
12:58 PM (35 minutes ago)￼
￼
Hi,

I took a look of the source code, there is an easy fix for the simdat dependency. However, the bigger problem is that the Graph class is no longer supported (see here), which means the implementation won't work even without the simdat dependency. I can fix the dependency issue soon, but I don't have time to modify the source code to use functional API at this moment... I am sorry. If you are interested in fixing it, let me know, we can cooperate together to make it work again and I will do my best to support you :).

**Comment by tammyyang** [comment]
Tammy Yang <tammy@dt42.io>
1:32 PM (0 minutes ago)￼

Hi,

The good news is, Squeezenet example does not depend on the old Graph API, I have fixed it. It should work now. If you just need the Keras implementation of the model, please import model.py only then you can avoid the dependency of simdat.
